spring.application.name=quartz
# 数据库的配置
spring.datasource.url=jdbc:h2:file:~/quartz-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
# quartz的配置
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always

