---
- hosts: all 
  become: yes
  vars_files:
    - users.yaml
  tasks:
    - name: create users
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        shell: /bin/bash
        state: present
      with_items: "{{ users }}"

    - name: upload ssh public key to users authorized keys file
      authorized_key:
        user: '{{ item.username }}'
        state: present
        manage_dir: yes
        key: "{{ lookup('file', './{{ item.keyfile }}') }}"
      with_items: "{{ users  }}"
