- name: In File
  hosts: all
  tasks:
  - name: Insert multiline content
    blockinfile:
      path: /home/test/conf.ini
      create: true
      block: |
        [database]
        server = localhost

        [memcache]
        buffersize = 23

  - name: Set the port value in database category
    lineinfile:
      insertafter: server
      line: port = 5432
      path: /home/test/conf.ini
  - name: Change configuration properties
    lineinfile:
      regexp: ^buffersize
      line: "buffersize = 50"
      path: /home/test/conf.ini
  - name: "Read a file content"
    shell: |
      cat /home/test/conf.ini
    register: file_content
  - name: "Print the file content to a console"
    debug:
      msg: "{{ file_content.stdout }}"
