ROOT := .
DIRS := lib intro sockets advio datafiles environ \
	termios fileio filedir signals

.PHONY: all clean

all:
	for i in $(DIRS); do \
		(cd $$i && echo "making $$i" && $(MAKE) ) || exit 1; \
	done

clean:
	for i in $(DIRS); do \
		(cd $$i && echo "cleaning $$i" && $(MAKE) clean) || exit 1; \
	done
